"""empty message

Revision ID: 025e035f726c
Revises: 6ebce1473889
Create Date: 2019-09-30 17:24:01.713374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025e035f726c'
down_revision = '6ebce1473889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')

    op.create_table('schedule',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('type', sa.String(length=16), nullable=True),
        sa.Column('trackId', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['trackId'], ['track.id']),
        sa.Column('laps', sa.Integer(), nullable=True),
        sa.Column('stages', sa.String(length=32), nullable=True),
        sa.Column('raceProcessed', sa.String(length=3), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_schedule_name'), 'schedule', ['name'], unique=False)

    op.drop_table('track_schedule_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')

    op.create_table('schedule',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('type', sa.String(length=16), nullable=True),
        sa.Column('laps', sa.Integer(), nullable=True),
        sa.Column('stages', sa.String(length=32), nullable=True),
        sa.Column('raceProcessed', sa.String(length=3), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_schedule_name'), 'schedule', ['name'], unique=False)

    op.create_table('track_schedule_association',
        sa.Column('trackId', sa.INTEGER(), nullable=False),
        sa.Column('scheduleId', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['scheduleId'], ['schedule.id'], ),
        sa.ForeignKeyConstraint(['trackId'], ['track.id'], ),
        sa.PrimaryKeyConstraint('trackId', 'scheduleId')
    )
    # ### end Alembic commands ###
