"""
Adds team, driver, contract and user tables with specified indexes.

Revision ID: 6886fb39a6d7
Revises: None
Create Date: 2019-09-10 00:59:42.441700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6886fb39a6d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('carManufacturer', sa.String(length=32), nullable=True),
    sa.Column('equipmentRating', sa.Float(), nullable=False),
    sa.Column('teamRating', sa.Float(), nullable=False),
    sa.Column('raceRating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_index(op.f('ix_team_owner'), 'team', ['owner'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('carNumber', sa.Integer(), nullable=True),
    sa.Column('shortRating', sa.Float(), nullable=False),
    sa.Column('shortIntermediateRating', sa.Float(), nullable=False),
    sa.Column('intermediateRating', sa.Float(), nullable=False),
    sa.Column('superSpeedwayRating', sa.Float(), nullable=False),
    sa.Column('restrictedTrackRating', sa.Float(), nullable=False),
    sa.Column('roadCourseRating', sa.Float(), nullable=False),
    sa.Column('overallRating', sa.Float(), nullable=False),
    sa.Column('potential', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_carNumber'), 'driver', ['carNumber'], unique=False)
    op.create_index(op.f('ix_driver_name'), 'driver', ['name'], unique=False)
    op.create_index(op.f('ix_driver_teamId'), 'driver', ['teamId'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('driverId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_status'), 'contract', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_status'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_driver_teamId'), table_name='driver')
    op.drop_index(op.f('ix_driver_name'), table_name='driver')
    op.drop_index(op.f('ix_driver_carNumber'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_team_owner'), table_name='team')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
