"""empty message

Revision ID: 6ebce1473889
Revises: 6886fb39a6d7
Create Date: 2019-09-27 17:01:20.584978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebce1473889'
down_revision = '6886fb39a6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('stages', sa.String(length=32), nullable=True),
    sa.Column('raceProcessed', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_name'), 'schedule', ['name'], unique=False)
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_name'), 'track', ['name'], unique=True)
    op.create_table('track_schedule_association',
    sa.Column('trackId', sa.Integer(), nullable=False),
    sa.Column('scheduleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheduleId'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['trackId'], ['track.id'], ),
    sa.PrimaryKeyConstraint('trackId', 'scheduleId')
    )
    op.drop_table('track_to_migrate')
    op.drop_table('schedule_to_migrate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_track_name', 'track_to_migrate', ['name'], unique=1)
    op.drop_table('track_schedule_association')
    op.drop_index(op.f('ix_track_name'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_schedule_name'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
