"""empty message

Revision ID: 7b02b47dcbba
Revises: c5f3025f6c6c
Create Date: 2019-10-25 15:08:59.950331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b02b47dcbba'
down_revision = 'c5f3025f6c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('driverId', sa.Integer(), nullable=True),
    sa.Column('carNumber', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_cars_series'), 'team_cars', ['series'], unique=False)
    op.create_table('team_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('driverId', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_drivers_series'), 'team_drivers', ['series'], unique=False)
    op.create_table('team_rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromId', sa.Integer(), nullable=True),
    sa.Column('toId', sa.Integer(), nullable=True),
    sa.Column('equipmentBonus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fromId'], ['team.id'], ),
    sa.ForeignKeyConstraint(['toId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_contract_status', table_name='contract')
    op.drop_table('contract')
    op.drop_index('ix_driver_carNumber', table_name='driver')
    op.drop_index('ix_driver_teamId', table_name='driver')
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.drop_column('driver', 'carNumber')
    op.drop_column('driver', 'teamId')
    op.add_column('team', sa.Column('personnelRating', sa.Float(), nullable=False))
    op.add_column('team', sa.Column('teamPerformance', sa.Float(), nullable=False))
    op.drop_index('team_id_uindex', table_name='team')
    op.drop_column('team', 'teamRating')
    op.drop_column('team', 'raceRating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('raceRating', sa.FLOAT(), nullable=False))
    op.add_column('team', sa.Column('teamRating', sa.FLOAT(), nullable=False))
    op.create_index('team_id_uindex', 'team', ['id'], unique=1)
    op.drop_column('team', 'teamPerformance')
    op.drop_column('team', 'personnelRating')
    op.add_column('driver', sa.Column('teamId', sa.INTEGER(), nullable=True))
    op.add_column('driver', sa.Column('carNumber', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'driver', 'team', ['teamId'], ['id'])
    op.create_index('ix_driver_teamId', 'driver', ['teamId'], unique=False)
    op.create_index('ix_driver_carNumber', 'driver', ['carNumber'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('length', sa.INTEGER(), nullable=True),
    sa.Column('salary', sa.FLOAT(), nullable=True),
    sa.Column('driverId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_status', 'contract', ['status'], unique=False)
    op.drop_table('team_rentals')
    op.drop_index(op.f('ix_team_drivers_series'), table_name='team_drivers')
    op.drop_table('team_drivers')
    op.drop_index(op.f('ix_team_cars_series'), table_name='team_cars')
    op.drop_table('team_cars')
    # ### end Alembic commands ###
