"""empty message

Revision ID: c5f3025f6c6c
Revises: 025e035f726c
Create Date: 2019-10-23 16:34:37.973776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f3025f6c6c'
down_revision = '025e035f726c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifying_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=True),
    sa.Column('driverId', sa.Integer(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('fastestLap', sa.Float(), nullable=True),
    sa.Column('rangeHits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['raceId'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifying_results_fastestLap'), 'qualifying_results', ['fastestLap'], unique=False)
    op.create_index(op.f('ix_qualifying_results_position'), 'qualifying_results', ['position'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=True),
    sa.Column('driverId', sa.Integer(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('lapsLed', sa.Integer(), nullable=True),
    sa.Column('fastestLap', sa.Float(), nullable=True),
    sa.Column('rangeHits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['raceId'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_results_fastestLap'), 'race_results', ['fastestLap'], unique=False)
    op.create_index(op.f('ix_race_results_lapsLed'), 'race_results', ['lapsLed'], unique=False)
    op.create_index(op.f('ix_race_results_position'), 'race_results', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_results_position'), table_name='race_results')
    op.drop_index(op.f('ix_race_results_lapsLed'), table_name='race_results')
    op.drop_index(op.f('ix_race_results_fastestLap'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_qualifying_results_position'), table_name='qualifying_results')
    op.drop_index(op.f('ix_qualifying_results_fastestLap'), table_name='qualifying_results')
    op.drop_table('qualifying_results')
    # ### end Alembic commands ###
