"""empty message

Revision ID: 7b02b47dcbba
Revises: c5f3025f6c6c
Create Date: 2019-10-25 15:08:59.950331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b02b47dcbba'
down_revision = 'c5f3025f6c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_cars_series'), 'team_cars', ['series'], unique=False)
    op.create_table('team_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_drivers_series'), 'team_drivers', ['series'], unique=False)
    op.create_table('team_rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('equipment_bonus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_contract_status', table_name='contract')
    op.drop_table('contract')
    op.drop_index('ix_driver_car_number', table_name='driver')
    op.drop_index('ix_driver_team_id', table_name='driver')
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.drop_column('driver', 'car_number')
    op.drop_column('driver', 'team_id')
    op.add_column('team', sa.Column('personnel_rating', sa.Float(), nullable=False))
    op.add_column('team', sa.Column('team_performance', sa.Float(), nullable=False))
    op.drop_index('team_id_uindex', table_name='team')
    op.drop_column('team', 'teamRating')
    op.drop_column('team', 'raceRating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('raceRating', sa.FLOAT(), nullable=False))
    op.add_column('team', sa.Column('teamRating', sa.FLOAT(), nullable=False))
    op.create_index('team_id_uindex', 'team', ['id'], unique=1)
    op.drop_column('team', 'team_performance')
    op.drop_column('team', 'personnel_rating')
    op.add_column('driver', sa.Column('team_id', sa.INTEGER(), nullable=True))
    op.add_column('driver', sa.Column('car_number', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'driver', 'team', ['team_id'], ['id'])
    op.create_index('ix_driver_team_id', 'driver', ['team_id'], unique=False)
    op.create_index('ix_driver_car_number', 'driver', ['car_number'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('length', sa.INTEGER(), nullable=True),
    sa.Column('salary', sa.FLOAT(), nullable=True),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_status', 'contract', ['status'], unique=False)
    op.drop_table('team_rentals')
    op.drop_index(op.f('ix_team_drivers_series'), table_name='team_drivers')
    op.drop_table('team_drivers')
    op.drop_index(op.f('ix_team_cars_series'), table_name='team_cars')
    op.drop_table('team_cars')
    # ### end Alembic commands ###
