"""empty message

Revision ID: 212dc4646286
Revises: 10564a20274e
Create Date: 2019-10-28 17:43:02.807032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '212dc4646286'
down_revision = '10564a20274e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('actual_equipment_rating', sa.Float(), nullable=False))
    op.add_column('team', sa.Column('used_equipment_rating', sa.Float(), nullable=False))
    op.drop_column('team', 'equipment_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('equipment_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('team', 'used_equipment_rating')
    op.drop_column('team', 'actual_equipment_rating')
    # ### end Alembic commands ###
