"""empty message

Revision ID: 404292ed7267
Revises: b45bc33583a0
Create Date: 2019-10-30 12:45:29.998061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404292ed7267'
down_revision = 'b45bc33583a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_cars', sa.Column('status', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_team_cars_status'), 'team_cars', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_cars_status'), table_name='team_cars')
    op.drop_column('team_cars', 'status')
    # ### end Alembic commands ###
