"""empty message

Revision ID: 4bf78c417e79
Revises: a280c42c8948
Create Date: 2019-11-11 19:38:27.789362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf78c417e79'
down_revision = 'a280c42c8948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('average_laps_under_caution', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'average_laps_under_caution')
    # ### end Alembic commands ###
