"""empty message

Revision ID: 56fc4fbaa46f
Revises: 404292ed7267
Create Date: 2019-10-30 13:39:15.640783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fc4fbaa46f'
down_revision = '404292ed7267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_name', table_name='team')
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.create_index('ix_team_name', 'team', ['name'], unique=False)
    # ### end Alembic commands ###
