"""empty message

Revision ID: a280c42c8948
Revises: ec7e06746e90
Create Date: 2019-11-11 16:25:25.623638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a280c42c8948'
down_revision = 'ec7e06746e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifying_results', sa.Column('fastest_time', sa.Float(), nullable=True))
    op.add_column('qualifying_results', sa.Column('top_speed', sa.Float(), nullable=True))
    op.drop_index('ix_qualifying_results_fastest_lap', table_name='qualifying_results')
    op.drop_index('ix_qualifying_results_position', table_name='qualifying_results')
    op.drop_column('qualifying_results', 'fastest_lap')
    op.drop_column('qualifying_results', 'range_hits')
    op.add_column('race_results', sa.Column('average_position', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('driver_rating', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('finish_position', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('highest_position', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('lap_lead_count', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('lap_lead_percentage', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('lowest_position', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('mid_race_position', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('start_position', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('top_15_lap_count', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('top_15_lap_percentage', sa.Integer(), nullable=True))
    op.add_column('race_results', sa.Column('total_lap_count', sa.Integer(), nullable=True))
    op.drop_index('ix_race_results_fastest_lap', table_name='race_results')
    op.drop_index('ix_race_results_laps_led', table_name='race_results')
    op.drop_index('ix_race_results_position', table_name='race_results')
    op.drop_column('race_results', 'fastest_lap')
    op.drop_column('race_results', 'laps_led')
    op.drop_column('race_results', 'position')
    op.drop_column('race_results', 'range_hits')
    op.add_column('schedule', sa.Column('average_position_change_per_lap', sa.Integer(), nullable=True))
    op.add_column('schedule', sa.Column('event_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'event_number')
    op.drop_column('schedule', 'average_position_change_per_lap')
    op.add_column('race_results', sa.Column('range_hits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('race_results', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('race_results', sa.Column('laps_led', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('race_results', sa.Column('fastest_lap', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_race_results_position', 'race_results', ['position'], unique=False)
    op.create_index('ix_race_results_laps_led', 'race_results', ['laps_led'], unique=False)
    op.create_index('ix_race_results_fastest_lap', 'race_results', ['fastest_lap'], unique=False)
    op.drop_column('race_results', 'total_lap_count')
    op.drop_column('race_results', 'top_15_lap_percentage')
    op.drop_column('race_results', 'top_15_lap_count')
    op.drop_column('race_results', 'start_position')
    op.drop_column('race_results', 'mid_race_position')
    op.drop_column('race_results', 'lowest_position')
    op.drop_column('race_results', 'lap_lead_percentage')
    op.drop_column('race_results', 'lap_lead_count')
    op.drop_column('race_results', 'highest_position')
    op.drop_column('race_results', 'finish_position')
    op.drop_column('race_results', 'driver_rating')
    op.drop_column('race_results', 'average_position')
    op.add_column('qualifying_results', sa.Column('range_hits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qualifying_results', sa.Column('fastest_lap', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_qualifying_results_position', 'qualifying_results', ['position'], unique=False)
    op.create_index('ix_qualifying_results_fastest_lap', 'qualifying_results', ['fastest_lap'], unique=False)
    op.drop_column('qualifying_results', 'top_speed')
    op.drop_column('qualifying_results', 'fastest_time')
    # ### end Alembic commands ###
