"""empty message

Revision ID: b45bc33583a0
Revises: 212dc4646286
Create Date: 2019-10-30 12:42:33.910087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45bc33583a0'
down_revision = '212dc4646286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'car_manufacturer',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_constraint('team_equipment_rented_from_fkey', 'team', type_='foreignkey')
    op.drop_column('team', 'equipment_rented_from')
    op.create_index(op.f('ix_team_cars_car_number'), 'team_cars', ['car_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_cars_car_number'), table_name='team_cars')
    op.add_column('team', sa.Column('equipment_rented_from', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('team_equipment_rented_from_fkey', 'team', 'team', ['equipment_rented_from'], ['id'])
    op.alter_column('team', 'car_manufacturer',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
