"""empty message

Revision ID: ec7e06746e90
Revises: 56fc4fbaa46f
Create Date: 2019-11-08 14:24:28.415116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7e06746e90'
down_revision = '56fc4fbaa46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifying_results', sa.Column('process_date_time', sa.DateTime(), nullable=True))
    op.add_column('qualifying_results', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qualifying_results', 'track', ['track_id'], ['id'])
    op.add_column('race_results', sa.Column('process_date_time', sa.DateTime(), nullable=True))
    op.add_column('race_results', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'race_results', 'track', ['track_id'], ['id'])
    op.alter_column('schedule', 'race_processed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'race_processed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'race_results', type_='foreignkey')
    op.drop_column('race_results', 'track_id')
    op.drop_column('race_results', 'process_date_time')
    op.drop_constraint(None, 'qualifying_results', type_='foreignkey')
    op.drop_column('qualifying_results', 'track_id')
    op.drop_column('qualifying_results', 'process_date_time')
    # ### end Alembic commands ###
